import { StyleSheet } from 'react-native';
import { BOOKING_COLORS as C } from '../constants/booking.constants';

export const passengerHomeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
    padding: 20,
    paddingTop: 60,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: C.navy,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 18,
    color: C.gray,
    marginBottom: 40,
  },
  bookButton: {
    backgroundColor: C.yellow,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    borderRadius: 16,
    gap: 10,
    marginBottom: 16,
  },
  bookButtonText: {
    color: C.navy,
    fontSize: 18,
    fontWeight: 'bold',
  },
  historyButton: {
    backgroundColor: C.navy,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 16,
    gap: 10,
  },
  historyButtonText: {
    color: C.white,
    fontSize: 16,
    fontWeight: '600',
  },
});

export const historyStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: C.bg,
  },
  loadingText: {
    marginTop: 12,
    color: C.gray,
    fontSize: 16,
    fontWeight: '500',
  },
  header: { padding: 20, paddingBottom: 10 },
  title: { fontSize: 24, fontWeight: 'bold', color: C.primary },
  tabRow: { flexDirection: 'row', paddingHorizontal: 20, gap: 10 },
  tab: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    backgroundColor: C.white,
  },
  tabActive: { backgroundColor: C.secondary },
  tabText: { color: C.gray, fontWeight: '600' },
  tabTextActive: { color: C.primary },
  list: { padding: 20 },
  emptyContainer: { padding: 40, alignItems: 'center' },
  emptyText: { color: C.gray, fontSize: 16, textAlign: 'center' },
  card: {
    backgroundColor: C.white,
    borderRadius: 12,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardLeft: {
    borderRightWidth: 1,
    borderColor: C.bg,
    paddingRight: 12,
    marginRight: 12,
    width: 75,
    alignItems: 'center',
  },
  date: { fontWeight: 'bold', color: C.primary, fontSize: 13 },
  time: { color: C.gray, fontSize: 11 },
  cardMiddle: { flex: 1, paddingRight: 8 },
  route: {
    fontWeight: '600',
    color: C.primary,
    marginBottom: 4,
    fontSize: 14,
  },
  driver: { color: C.gray, fontSize: 12 },
  badge: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 20,
    minWidth: 80,
    alignItems: 'center',
  },
  badgeText: { color: C.white, fontWeight: 'bold', fontSize: 10 },
});

export const passengerDetailsStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  container: { flex: 1 },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: C.bg,
  },
  loadingText: {
    marginTop: 12,
    color: C.gray,
    fontSize: 16,
    fontWeight: '500',
  },
  errorText: { fontSize: 18, color: C.gray, marginBottom: 16 },
  backButton: {
    backgroundColor: C.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  backButtonText: { color: C.white, fontWeight: 'bold' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: C.white,
    borderBottomWidth: 1,
    borderColor: C.border,
    gap: 10,
  },
  iconBack: { marginRight: 5 },
  backText: { color: C.primary, fontSize: 16, fontWeight: 'bold' },
  title: { fontSize: 18, fontWeight: 'bold', color: C.primary, flex: 1 },
  statusBadge: { paddingVertical: 4, paddingHorizontal: 8, borderRadius: 12 },
  statusBadgeText: { color: C.white, fontSize: 11, fontWeight: 'bold' },
  map: { width: '100%', height: 280 },
  mapPlaceholder: {
    width: '100%',
    height: 280,
    backgroundColor: C.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapPlaceholderText: { color: C.gray },
  driverCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.white,
    margin: 15,
    padding: 15,
    borderRadius: 12,
    gap: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  driverAvatar: { width: 50, height: 50, borderRadius: 25 },
  driverInfo: { flex: 1 },
  driverName: { fontSize: 16, fontWeight: 'bold', color: C.primary },
  driverCar: { fontSize: 14, color: C.gray },
  driverPhone: { fontSize: 13, color: C.primary, marginTop: 2 },
  searchingCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.white,
    margin: 15,
    padding: 18,
    borderRadius: 12,
    gap: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  searchingText: { fontSize: 14, color: C.gray, fontWeight: '500' },
  card: {
    padding: 15,
    backgroundColor: C.white,
    marginHorizontal: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  cardText: { fontSize: 16, color: C.gray, marginBottom: 8 },
  fareText: {
    color: C.primary,
    fontWeight: 'bold',
    fontSize: 18,
    marginTop: 4,
  },
  buttonRow: { padding: 15 },
  button: {
    padding: 16,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: C.danger,
  },
  buttonDisabled: { opacity: 0.7 },
  buttonText: {
    color: C.white,
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
  },
});

export const requestsStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg, padding: 16 },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: C.bg,
  },
  loadingText: {
    marginTop: 12,
    color: C.gray,
    fontSize: 16,
    fontWeight: '500',
  },
  title: { fontSize: 24, fontWeight: 'bold', color: C.navy, marginBottom: 16 },
  card: {
    backgroundColor: C.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 2,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  fare: { fontSize: 22, fontWeight: 'bold', color: C.navy },
  badge: {
    backgroundColor: C.yellow,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  badgeText: { fontSize: 12, fontWeight: 'bold', color: C.navy },
  routeRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  dots: { alignItems: 'center', justifyContent: 'center' },
  dot: { width: 10, height: 10, borderRadius: 5 },
  pickupDot: { backgroundColor: C.yellow },
  dropoffDot: { backgroundColor: C.navy },
  line: { width: 2, height: 20, backgroundColor: C.line, marginVertical: 4 },
  routeTextWrap: { flex: 1 },
  pickup: { fontSize: 15, color: C.navy, marginBottom: 6 },
  dropoff: { fontSize: 15, color: C.gray },
  label: { fontWeight: '600' },
  footerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderColor: C.mutedBorder,
    paddingTop: 12,
  },
  infoPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: C.mutedBg,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  infoText: { fontSize: 12, color: C.navy, fontWeight: '600' },
  accept: { fontSize: 14, color: C.yellow, fontWeight: 'bold' },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  emptyIcon: { opacity: 0.3, marginBottom: 12 },
  emptyText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: C.navy,
    marginBottom: 6,
    textAlign: 'center',
  },
  emptySubtitle: { fontSize: 14, color: C.gray, textAlign: 'center' },
  listContent: { paddingBottom: 20 },
});

export const driverDetailsStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  container: { flex: 1 },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: C.bg,
  },
  loadingText: {
    marginTop: 12,
    color: C.gray,
    fontSize: 16,
    fontWeight: '500',
  },
  errorText: { fontSize: 18, color: C.gray, marginBottom: 16 },
  backButton: {
    backgroundColor: C.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
  },
  backButtonText: { color: C.white, fontWeight: 'bold' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: C.white,
    borderBottomWidth: 1,
    borderColor: C.border,
    gap: 10,
  },
  iconBack: { marginRight: 5 },
  backText: { color: C.primary, fontSize: 16, fontWeight: 'bold' },
  title: { fontSize: 18, fontWeight: 'bold', color: C.primary, flex: 1 },
  statusBadge: { paddingVertical: 4, paddingHorizontal: 8, borderRadius: 12 },
  statusBadgeText: { color: C.white, fontSize: 11, fontWeight: 'bold' },
  map: { width: '100%', height: 300 },
  mapPlaceholder: {
    width: '100%',
    height: 300,
    backgroundColor: C.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapPlaceholderText: { color: C.gray },
  card: {
    padding: 15,
    backgroundColor: C.white,
    margin: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
  },
  cardText: { fontSize: 16, color: C.gray, marginBottom: 8 },
  labelText: { fontWeight: '600', color: C.primary },
  fareText: {
    color: C.primary,
    fontWeight: 'bold',
    fontSize: 18,
    marginTop: 4,
  },
  actionsCard: { paddingHorizontal: 15 },
  buttonRow: { flexDirection: 'row', gap: 12 },
  button: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  declineButton: { backgroundColor: C.danger },
  acceptButton: { backgroundColor: C.success },
  startButton: { backgroundColor: C.primary },
  completeButton: { backgroundColor: C.success },
  buttonDisabled: { opacity: 0.7 },
  fullWidthButton: {
    width: '100%',
    padding: 16,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: C.white,
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.white,
    padding: 16,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: C.gray,
    borderWidth: 1,
    borderColor: C.border,
    gap: 8,
  },
  infoBoxText: { fontSize: 15, color: C.gray, fontWeight: '500', flex: 1 },
});
